name: PR - Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  run_pr-template:
    name: PR - Build and Deploy
    # SH-ToDo - Revert
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@OPENIG-8961-separate-ig-instance-deployments-for-authorisation-server-and-resource-server
    secrets: inherit
    with:
      componentName: secure-api-gateway-fapi-pep-as
      dockerTag: pr-${{ github.event.number }}