name: Merge Notification
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    name: Push Slack Notification
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_SBAT_NOTIFY_SLACK }}
          SLACK_COLOR: ${{ job.status }}